# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

required = [
  "k8s.io/apimachinery/pkg/util/sets/types",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "github.com/knative/pkg/codegen/cmd/injection-gen",
  "github.com/knative/caching/pkg/apis/caching",
  "github.com/knative/test-infra/scripts",
  "github.com/knative/test-infra/tools/dep-collector",
]

[[override]]
  name = "gopkg.in/yaml.v2"
  version = "v2.2.1"

[[override]]
  name = "k8s.io/klog"
  version = "v0.2.0"

[[override]]
  name = "k8s.io/gengo"
  revision = "e17681d19d3ac4837a019ece36c2a0ec31ffe985"

[[override]]
  name = "go.uber.org/zap"
  revision = "67bc79d13d155c02fd008f721863ff8cc5f30659"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.6"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.6"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.12.6"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.6"

[[constraint]]
  name = "github.com/knative/caching"
  # HEAD as of 2019-06-08
  revision = "b6c8f4851e3fb13987782cf8014316141e42fbd3"

[[override]]
  name = "github.com/knative/pkg"
  branch = "release-0.7"

[[override]]
  name = "contrib.go.opencensus.io/exporter/stackdriver"
  # HEAD as of 2019-02-11
  # Needed because this includes a fix to support Stackdriver built-in metrics
  revision = "c06c82c832edca4eaf7b0241bd655560a1be0346"

[[override]]
  name = "golang.org/x/net"
  # Override opencensus "master" constraint
  branch = "release-branch.go1.9"

[[override]]
  name = "github.com/golang/protobuf"
  # Lock the version of protobuf to keep things building.
  revision = "aa810b61a9c79d51363740d207bb46cf8e620ed5"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "github.com/knative/caching"
  unused-packages = false
  non-go = false

[[prune.project]]
  name = "github.com/knative/test-infra"
  non-go = false

 [[prune.project]]
  name = "github.com/knative/pkg"
  unused-packages = false
  non-go = false
