apiVersion: kan.k8s.io/v1beta1
kind: Task
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: build-push
spec:
    inputs:
        sources:
            - name: workspace
        params:
            - name: pathToDockerFile
              type: string
    outputs:
        artifacts:
            - name: builtImage
              type: image
              storeKey: registry
    buildSpec:
        template:
            name: kaniko
            arguments:
                - name: DOCKERFILE
                  value: ${pathToDockerFile}
                - name: REGISTRY
                  value: ${registry}
