apiVersion: kan.k8s.io/v1beta1
kind: PipelineParams
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: pipelineparams-sample
spec:
    serviceAccount: 'demoServiceAccount'
    sources:
        - name: 'guestbook'
          type: 'github'
          url: 'github.com/kubernetes/examples'
          serviceAccount: 'githubServiceAccount'
          branch: 'master'
          commit: 'HEAD'
        - name: 'redis-docker'
          type: 'github'
          url: 'github.com/GoogleCloudPlatform/redis-docker/blob/master/4/debian9/4.0/Dockerfile'
          serviceAccount: 'githubServiceAccount'
          branch: 'master'
          commit: 'HEAD'
        - name: 'kritis'
          type: 'github'
          url:  'github.com/grafeas/kritis'
          branch: 'master'
          commit: 'HEAD'
    artifactStores:
        - name: 'prodRegistry'
          type: 'imageRegistry'
          url: 'gcr.io/demo'
        - name: 'stagingRegistry'
          type: 'imageRegistry'
          url: 'gcr.io/demo-staging'
    clusters:
        - name: 'testCluster'
          type: 'gke'
          name: 'test'
          endpoint: 'https://prod.gke.corp.com'
        - name: 'stagingCluster'
          type: 'gke'
          name: 'staging'
          endpoint: 'https://staging.gke.corp.com'
    volumes:
        - name: gac
          source: $(workspace)/config/gac.json
          destination: gac.json
        - name: cloudconfig
          source: $(workspace)/config/gcloud
          destination: /root/.config/gcloud
    results:
        runs:
        - name: 'runsBucket'
          type: 'gcs'
          url: 'gcs://somebucket/results/runs'
          token: 'todo'
        logs:
        - name: 'logBucket'
          type: 'gcs'
          url: 'gcs://somebucket/results/logs'
          token: 'todo'
        tests:
        - name: 'testBucket'
          type: 'gcs'
          url: 'gcs://somebucket/results/tests'
          token: 'todo'
